### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by vikasksrivastava** [t9md/atom-markdown-toc-auto#16]
[Enter steps to reproduce:]

1. On MAC Ctr + Shift + P and selecting Auto ToC 

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [markdown-toc-auto](https://github.com/t9md/atom-markdown-toc-auto) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/vikassri/.atom/packages/markdown-toc-auto/lib/utils.js:68

TypeError: Cannot read property 'startsWith' of undefined
    at isMarkdownHeader (/packages/markdown-toc-auto/lib/utils.js:68:72)
    at editor.scan (/packages/markdown-toc-auto/lib/utils.js:75:10)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1118:15)
    at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1073:25)
    at TextEditor.scan (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3530:30)
    at scanHeaders (/packages/markdown-toc-auto/lib/utils.js:74:10)
    at insertToc (/packages/markdown-toc-auto/lib/utils.js:131:23)
    at Object.insertTocAtPoint (/packages/markdown-toc-auto/lib/utils.js:155:3)
    at /packages/markdown-toc-auto/lib/main.js:22:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:10.7.0 core:save (input.hidden-input)
     -0:08.1.0 core:backspace (input.hidden-input)
     -0:06.3.0 command-palette:toggle (input.hidden-input)
     -0:04.2.0 core:confirm (input.hidden-input)
     -0:04.2.0 markdown-toc-auto:insert-toc (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-ide-ui 0.12.0 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-ui 1.3.3 
docker 0.8.0 
file-icons 2.1.21 
fold-functions 0.5.0 
fold-lines 0.2.2 
foldingtext-for-atom 0.9.2 
ftp-remote-edit 0.12.12 
git-time-machine 2.0.1 
ide-python 0.9.2 
ide-yang 0.1.0 
intentions 1.1.5 
language-cisco 1.4.0 
language-docker 1.1.8 
language-markdown 0.25.1 
language-yang 0.2.0 
linter 2.2.0 
linter-markdown 5.2.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
markdown-image-paste 2.5.2 
markdown-img-paste 0.3.9 
markdown-preview-enhanced 0.15.6 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-toc 0.4.2 
markdown-toc-auto 0.9.0 
markdown-writer 2.7.3 
platformio-ide-terminal 2.8.1 
python-autopep8 0.1.3 
python-indent 1.1.5 
recursive-folding 0.2.2 
remember-folds 0.3.0 
remote-ftp 2.2.0 
set-syntax 0.4.0 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
tidy-markdown 3.0.1 
windows-carriage-return-remover 0.1.3 
xml-formatter 0.11.0 
```

**Comment by darkdragon-001** [comment]
I experience the same problem from time to time. Because of this, I can't save some files any more.

I found out that I can circumvent this problem by avoiding character sequences which are matched by the following regex: `^#(?![ #])`.

Unfortunately, I couldn't find out how to replicate the error state reliably...
